name: Clean up PR environment on close

on: pull_request

jobs:
  clean-up-environment:
    runs-on: ubuntu-latest
    steps:
    - name: 'Trigger an Azure Pipeline to cleanup a PR environment'
      uses: Azure/pipelines@releases/v1
      with:
        azure-devops-project-url: 'https://microsofthealthoss.visualstudio.com/FhirServer'
        azure-pipeline-name: 'Remove PR Environment' 
        azure-devops-token: '${{ secrets.AZURE_DEVOPS_TOKEN }}'
